Add missing &&

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -32,7 +32,7 @@ jobs:
       - name: Check if file exists
         run: |
           for FILE in test/popmap_test/*.fq.gz; do
-            test -f $FILE || (echo "File $FILE not found" exit 1)
+            test -f $FILE || (echo "$FILE not found" && exit 1)
           done
 
   build:
